from main import *

def refresheverything(self):
        self.combo()
        self.search_stock_category()
        #ban(self)
        
        self.addstock2()
        self.recipt()
        self.Netprofit_Margin()
        self.Markup()
        self.Margin()
        #self.ui.lineEdit_18.setValidator(self.onlyInt)

        self.capital_employed()
        self.scroll()
        self.sum_fix_exp()
        self.sum_var_exp()
        self.total_liability()
        self.sum_long_term()
        self.sum_short_term()
        self.sumCurrent_asset()
        self.total_expenses()
        self.sumFixed_asset()
        self.total_asset()
        self.displ()
        self.gross_profit()
        self.net_profit()

        self.working_capital()
        self.debt_ratio()
        self.current_ratio()
        self.total_sales()
        self.openbtn()

        # self.Quantity()

        # self.s_P()
        # self.s_t()
        self.pos_details()
        self.most_sold_table()
        # self.most_soldbydate()
        self.autocompleter()
        self.auto()
        
        #self.addbtnstock()
        # self.auto2()
        self.search_stock_category()
        self.pos_line()
        self.pos_line_due()
        self.load_postable_data()
        
        self.reset_postable_button()
        # self.vat_changebutton()

        self.printerbtn()
        self.combo()
        self.reoder_limit()
        self.profit_lossbtn()
        self.recip_detail()
        self.reciptload()
        self.keystroke()
        self.save_payment_btn()
        self.cae()
        self.fae()
        self.ltl()
        self.stl()
        self.fee()
        self.vee()
        # self.sales()
        self.return_order_btn()
        self.update1()
        self.export_to_excel()
        self.bizdetail_btn()
        self.taxset()
        self.reset_solditems_postable()
        self.ui.dateEdit.editingFinished.connect(lambda: self.date_method())
        orders_function.setButtons(self)
        orders_function.auto_completer(self)
        Table_resizeing.resize_tables(self)
        orders_function.orders_label(self)
        payment.combo_payments(self)
        self.combo_pay()
        self.update_order_btn()

        self.clientbtn()
        self.income()

def table_refresh(self):
        self.loaddata2()
        self.loaddata()
        self.loaddata3()
        self.loaddata4()
        self.loaddata5()
        self.loaddata6()
        
        self.loaddata9()
        self.loaddata13()